config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :comics, only: [:index] do
    member do
      patch 'favorite'
    end
  end

  resources :characters do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:search]

  def search
  end

  private
  def set_character
    return unless params[:name]

    cache_key = "character_#{params[:name].downcase}"
    @character = Rails.cache.fetch(cache_key, expires_in: 12.hours) do
      FetchCharacterService.new.call(params[:name])
    end
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  def index
    session[:favorites] ||= []

    @comics = results
    @comics = paginate(@comics)
  end

  def favorite
    session[:favorites] ||= []
    id = params[:id]

    session[:favorites].include?(id) ? session[:favorites].delete(id) : session[:favorites] << id

    head :ok
  end

  private

  def paginate(comics)
    page = [params[:page].to_i, 1].max
    per_page = 10

    WillPaginate::Collection.create(page.to_i, per_page, comics.size) do |pager|
      pager.replace comics[pager.offset, pager.per_page]
    end
  end

  def results
    cached_results = Rails.cache.read('comics_data')
    return cached_results if cached_results

    marvel_service = FetchComicBooksService.new.call
    return marvel_service if marvel_service.kind_of?(Array) && marvel_service.empty?

    Rails.cache.write('comics_data', marvel_service, expires_in: 1.day)
    results
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
  def is_favorite?(comic_id)
    session[:favorites].include?(comic_id.to_s)
  end
end

app/views/characters/_character.html.erb
<div class="character-item">
  <% if @character.success %>
    <img src="<%= @character.thumbnail %>" alt="character thumbnail" class="comic-image">
  <% else %>
    <img src="https://lightwidget.com/wp-content/uploads/localhost-file-not-found-480x480.avif" alt="comic thumbnail" class="comic-image">
  <% end %>

  <div class="character-infos">
  <p class="character-name"><%= @character.name %></p>
  <p><%= @character.description %></p>
  </div>
</div>

app/views/characters/search.html.erb
<div class="character-container">
  <% if @character.present? %>
    <%= render partial: 'character', locals: { character: @character } %>
  <% end %>
</div>

app/views/comics/_character.html.erb
<div class="character-item">
  <% if @character.success %>
    <img src="<%= @character.thumbnail %>" alt="character thumbnail" class="comic-image">
  <% else %>
    <img src="https://lightwidget.com/wp-content/uploads/localhost-file-not-found-480x480.avif" alt="comic thumbnail" class="comic-image">
  <% end %>

    <div class="character-infos">
      <p class="character-name"><%= @character.name %></p>
      <p><%= @character.description %></p>
    </div>
</div>

app/views/comics/_comic.html.erb
<div class="comic-item">
  <img src="<%= comic[:thumbnail] %>" alt="comic thumbnail" class="comic-image">

  <%= render partial: 'favorite', locals: { comic: comic } %>

  <div class="comic-name-tag">
    <%= comic[:title] %>
  </div>
</div>

app/views/comics/_comics_list.html.erb
<div id="comics-container" class="comics-grid">
  <% @comics.each do |comic| %>
    <%= render partial: 'comic', locals: { comic: comic } %>
  <% end %>
</div>

<%= will_paginate @comics, :page_links => false %>

app/views/comics/_favorite.html.erb
<%= link_to favorite_comic_path(comic[:id]),
            remote: true,
            data: { turbo_method: "patch" },
            class: "favorite-toggle #{'favorite-fill' if is_favorite?(comic[:id])}" do %>
  <%= image_tag 'heart-svgrepo-com.svg', alt: 'Favorite comics', class: 'favorite-icon' %>
<% end %>

app/views/comics/_try_again.html.erb
<div class="refresh-btn">
  <%= link_to root_path do %>
    Try again!
  <% end %>
</div>

app/views/comics/index.html.erb
<%= turbo_frame_tag :marvel_data do %>
  <div class="index-container">
    <% if @comics.empty? %>
      <%= render partial: 'comics/try_again' %>
    <% else %>
      <%= render partial: 'comics/comics_list', locals: { comics: @comics } %>
    <% end %>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      document.querySelectorAll('.favorite-toggle').forEach((favorite) => {
        favorite.addEventListener('click', (e) => {
          e.currentTarget.classList.toggle('favorite-fill');
        })
      })
    });
  </script>
<% end %>

app/views/comics/show.html.erb
<div class="index-container">

  <div class="search-container">
    <h1 class="title">Marvel</h1>
    <%= form_tag(comics_index_path, method: :get, class: "search-bar") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Comics" %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>

  <div class="comics-grid">
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvellApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="index-container">
  <%= turbo_frame_tag :marvel_data, src: comics_path, loading: :lazy do %>
    <div class="card mt-3">
      <div class="card-body">
        <div class="loading-ring hidden justify-content-center align-items-center py-1">
          <div class="spinner-border spinner-border-sm" role="status">
            <h3 class="loading sr-only">Loading...</h3>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="search-container">
  <%= link_to root_path do %>
    <%= image_tag 'marvel_logo.png', alt: 'Marvel Logo' %>
  <% end %>

  <%= form_with url: search_characters_path, method: :get, local: true, html: { class: 'search-bar', id: 'search-form' } do |form| %>
    <%= form.text_field :name, placeholder: "Search character" %>
  <% end %>
</div>